backend:
  resources:
    limits:
      cpu: 1000m
      memory: 1536Mi
    requests:
      cpu: 250m
      memory: 512Mi
  env:
    environment: production
    debug: "False"
frontend:
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m 
      memory: 256Mi 
ingress:
  annotations:
    cert-manager.io/cluster-issuer: property-rag-ca-issuer                                                              
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"                                                                  
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"                                                               
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"                                                               
    nginx.ingress.kubernetes.io/websocket-services: "frontend-service"