apiVersion: ENC[AES256_GCM,data:SAg=,iv:8Az258HMRtDXTjsb2m6MIxu6PenEBlJBmnafX0XKQjg=,tag:aCmpyEYT/+/MYplZGtDEAA==,type:str]
kind: ENC[AES256_GCM,data:6ooEQNMa,iv:7ipzCnICS7Tv3fQ4wpctUyRo8OA2m/PmhyzdIjW+UCs=,tag:gpUtpWteZ/ex4gNFhYLvKA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:+ap16qtciUTwR/N4pAfr2oJMcsM=,iv:bsiXCCh1M4ox9Hq75GkLeZMCzvmTeQ8qx0oBrroZRCM=,tag:Og82X1yutXKThxB+6twK9g==,type:str]
    namespace: ENC[AES256_GCM,data:PxLI88VE+hAmQ3iw,iv:5Nl9O+qCpHGapn6T+gjIExAeQ9Dg4kKBmXGiV/INujo=,tag:nAchcRNsPVvXieBLE/PXfA==,type:str]
type: ENC[AES256_GCM,data:Es1zdMby,iv:1haXmFuQjP9YZ2Cl0FgjNLMNa21+xcS5KmkpXMWFkPw=,tag:Nl4oM3SdubARFIY38fY1Fw==,type:str]
stringData:
    GEMINI_API_KEY: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14va96fqjnaj0695mad0cfjsfa69kzu8e9xukurmzc6zqhlvsly6qfpwdk6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4MlpxRml6NkQvaEF2aHNm
            ZytKNjliQ3VaR0plejdJdVRSMDVERkRRMlNVCkFPaDhpaW5PYWtUZTVtY25mM2RI
            R3ZSNWJDeFI5WWFObG1WSkV4MmRpQjAKLS0tIC80WUFWWlFqdit1QXNuMnB5ZVBB
            cE5ubzlaeURicUFUb0xhNXphZ2ZtcTQKfAoFmbPJyI68QQJ5EsjzhXfEdzKkM+jl
            waHYXaCxpQbdy1LfL75O2gAt7P9OqrDmm9ppcfmFnWdcqzzUVAVqdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-08T07:15:52Z"
    mac: ENC[AES256_GCM,data:OiCVc00ru6zvJYEALpDUnIZJnQududWdu5FCPzmgn/sMBdZG0Syj51F54kik7RCN4yY9mjDYiMBsczBL1cxLaKWtrSBTTui3vVzm/7B8f+T4LU4XzNFoeRMdL5J9rN975W+uDfsz/kSsMIb+t12zbcRGvQFDrmop5yeNShuSJC0=,iv:fJtOrsnTgrXene835WFQ0zlJtR9v2gA4c8jnRFOri5Y=,tag:ukzI4gPg2pVAIfgsM53f9g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
