apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.chroma.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: backend
    {{- include "property-rag.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.chroma.accessMode }}
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.chroma.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.analytics.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: backend
    {{- include "property-rag.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.analytics.accessMode }}
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.analytics.size }}